name: Run security check on Go code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
            go-version: '1.21.x'
      - name: Install dependencies
        run: go get ./...
      - name: Run unit tests, benchmarks, and fuzz tests
        run: make github_actions
